---
version: '3'
services:
  application:
    build: ./application
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_AUTH0_DOMAIN=ariel17.auth0.com
      - REACT_APP_AUTH0_CLIENT_ID=GU91ADkwV3Cztq4vEnGGyiPkuvFtHzZ1
      - REACT_APP_REDIRECT_URL=http://localhost:3000
  api:
    build: ./api
    ports:
      - "8080:8080"
